[[Xorg_xextproto]]
arch = "armv7l"
git-tree-sha1 = "f81a8aa8b1d9b3827befbd78005c39f755126b47"
libc = "glibc"
os = "linux"

    [[Xorg_xextproto.download]]
    sha256 = "21a83a17c7a075953175b04dd0ccfbafb285fbb908d38f295867174951f698ec"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xextproto_jll.jl/releases/download/Xorg_xextproto-v7.3.0+0/Xorg_xextproto.v7.3.0.arm-linux-gnueabihf.tar.gz"
[[Xorg_xextproto]]
arch = "aarch64"
git-tree-sha1 = "8334efc7b16aa42b14f2fe68e1fd1d006695ef85"
libc = "musl"
os = "linux"

    [[Xorg_xextproto.download]]
    sha256 = "9f1b01045b10e6e01850a9be23c4b43101f7bca49872eef2d3061d59e7fb0963"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xextproto_jll.jl/releases/download/Xorg_xextproto-v7.3.0+0/Xorg_xextproto.v7.3.0.aarch64-linux-musl.tar.gz"
[[Xorg_xextproto]]
arch = "i686"
git-tree-sha1 = "6b4cf3a1613511f732ccdba0c65fe8bb94640013"
libc = "musl"
os = "linux"

    [[Xorg_xextproto.download]]
    sha256 = "74da46273e85d38ffc676825454b2872112620e2a77531481857ea95b1464bfe"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xextproto_jll.jl/releases/download/Xorg_xextproto-v7.3.0+0/Xorg_xextproto.v7.3.0.i686-linux-musl.tar.gz"
[[Xorg_xextproto]]
arch = "i686"
git-tree-sha1 = "dad64b1712725e3987e57adb799eb5045837d565"
libc = "glibc"
os = "linux"

    [[Xorg_xextproto.download]]
    sha256 = "e2c142a6191fc7f8a7d91a67d4fa4efbb81479ad8bc3a7f32d1fd6b669d524ea"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xextproto_jll.jl/releases/download/Xorg_xextproto-v7.3.0+0/Xorg_xextproto.v7.3.0.i686-linux-gnu.tar.gz"
[[Xorg_xextproto]]
arch = "x86_64"
git-tree-sha1 = "2007cc6dc09cb9c48088d8332e08ed85c6592fbf"
os = "freebsd"

    [[Xorg_xextproto.download]]
    sha256 = "b91e5369c14550ad9e6b7a52a4cb8aeeca528cd941e57f8b7317ef048d9b57a8"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xextproto_jll.jl/releases/download/Xorg_xextproto-v7.3.0+0/Xorg_xextproto.v7.3.0.x86_64-unknown-freebsd11.1.tar.gz"
[[Xorg_xextproto]]
arch = "powerpc64le"
git-tree-sha1 = "1cce41cc30542091b01d742ecab1436eab11c24d"
libc = "glibc"
os = "linux"

    [[Xorg_xextproto.download]]
    sha256 = "b69dbcae0a0537da28a946fd5442073a69f657447fc8a9c222bdcbf68c8d0d83"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xextproto_jll.jl/releases/download/Xorg_xextproto-v7.3.0+0/Xorg_xextproto.v7.3.0.powerpc64le-linux-gnu.tar.gz"
[[Xorg_xextproto]]
arch = "armv7l"
git-tree-sha1 = "88950b4139ac71abcf2b10a15be39e61d4b6e2f1"
libc = "musl"
os = "linux"

    [[Xorg_xextproto.download]]
    sha256 = "072a1d21040ed62ca3beabbf9875beade9362d3fa5052bf2850d5d707ebdba39"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xextproto_jll.jl/releases/download/Xorg_xextproto-v7.3.0+0/Xorg_xextproto.v7.3.0.arm-linux-musleabihf.tar.gz"
[[Xorg_xextproto]]
arch = "aarch64"
git-tree-sha1 = "43adb3c5ea912ec5e0d309e7f478dae9eb9026fa"
libc = "glibc"
os = "linux"

    [[Xorg_xextproto.download]]
    sha256 = "30dd2441a99d7da9b6ed1dd1bee16b5e76946ca2d4e3b92a6fe1630ab0203204"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xextproto_jll.jl/releases/download/Xorg_xextproto-v7.3.0+0/Xorg_xextproto.v7.3.0.aarch64-linux-gnu.tar.gz"
[[Xorg_xextproto]]
arch = "x86_64"
git-tree-sha1 = "b8bb124ec4bcc3178a57bd6270dd5c5b795c035f"
libc = "glibc"
os = "linux"

    [[Xorg_xextproto.download]]
    sha256 = "c7850fc2a58ca85e025e2c3d84686d2515b7b56010c57de3c36d9237bfeaf205"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xextproto_jll.jl/releases/download/Xorg_xextproto-v7.3.0+0/Xorg_xextproto.v7.3.0.x86_64-linux-gnu.tar.gz"
[[Xorg_xextproto]]
arch = "x86_64"
git-tree-sha1 = "c1ed3694c4173451e3bf67f2f9b8505a51d169ec"
libc = "musl"
os = "linux"

    [[Xorg_xextproto.download]]
    sha256 = "9d9b337049acbcaf06224fa9731112b2471805f30bce97f47156510438635614"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xextproto_jll.jl/releases/download/Xorg_xextproto-v7.3.0+0/Xorg_xextproto.v7.3.0.x86_64-linux-musl.tar.gz"
